channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - pip:
    - z3-solver==4.12.3.0
    - importlib-resources
    - matplotlib
    - plotly
    - kaleido
    - ipywidgets
    - isodate
    - ipympl
    - psutil
    - XlsxWriter
    - coverage
    - -e .
